const countryData = {
    "AE": ["United Arab Emirates", "Emirati Arabi Uniti", "Émirats arabes unis", "UAE", "Arabia Saudita", "Arabie saoudite"],
    "AF": ["Afghanistan", "Afghanistan", "Afghanistan"],
    "AL": ["Albania", "Albania", "Albanie"],
    "AM": ["Armenia", "Armenia", "Arménie"],
    "AO": ["Angola", "Angola", "Angola"],
    "AR": ["Argentina", "Argentina", "Argentine"],
    "AT": ["Austria", "Austria", "Autriche"],
    "AU": ["Australia", "Australia", "Australie"],
    "AT": ["Austria", "Austria", "Autriche"],
    "AZ": ["Azerbaijan", "Azerbaigian", "Azerbaïdjan"],
    "BA": ["Bosnia and Herzegovina", "Bosnia ed Erzegovina", "Bosnie-Herzégovine", "Bosnie Herzegovine", "Bosnia Erzegovina"],
    "BD": ["Bangladesh", "Bangladesh", "Bangladesh"],
    "BE": ["Belgium", "Belgio", "Belgique"],
    "BF": ["Burkina Faso", "Burkina Faso", "Burkina Faso"],
    "BG": ["Bulgaria", "Bulgaria", "Bulgarie"],
    "BI": ["Burundi", "Burundi", "Burundi"],
    "BJ": ["Benin", "Benin", "Bénin"],
    "BN": ["Brunei", "Brunei", "Brunéi"],
    "BO": ["Bolivia", "Bolivia", "Bolivie"],
    "BR": ["Brazil", "Brasile", "Brésil", "Brasil"],
    "BS": ["Bahamas", "Bahamas", "Bahamas"],
    "BT": ["Bhutan", "Bhutan", "Bhoutan", "Boutan"],
    "BW": ["Botswana", "Botswana", "Botswana"],
    "BY": ["Belarus", "Bielorussia", "Biélorussie"],
    "BZ": ["Belize", "Belize", "Belize"],
    "CA": ["Canada", "Canada", "Canada"],
    "CD": ["Democratic Republic of the Congo", "Repubblica Democratica del Congo", "République démocratique du Congo", "Congo"],
    "CF": ["Central African Republic", "Repubblica Centrafricana", "République centrafricaine", "Republique centre africaine", "Repubblica Centro africana"],
    "CG": ["Republic of the Congo", "Repubblica del Congo", "République du Congo"],
    "CH": ["Switzerland", "Svizzera", "Suisse"],
    "CI": ["Ivory Coast", "Costa d'Avorio", "Côte d'Ivoire"],
    "CL": ["Chile", "Cile", "Chili"],
    "CM": ["Cameroon", "Camerun", "Cameroun"],
    "CN": ["China", "Cina", "Chine"],
    "CO": ["Colombia", "Colombia", "Colombie"],
    "CR": ["Costa Rica", "Costa Rica", "Costa Rica", "Costarica"],
    "CU": ["Cuba", "Cuba", "Cuba"],
    "CY": ["Cyprus", "Cipro", "Chypre"],
    "CZ": ["Czech Republic", "Repubblica Ceca", "République tchèque"],
    "DE": ["Germany", "Germania", "Allemagne"],
    "DJ": ["Djibouti", "Gibuti", "Djibouti"],
    "DK": ["Denmark", "Danimarca", "Danemark"],
    "DO": ["Dominican Republic", "Repubblica Dominicana", "République dominicaine"],
    "DZ": ["Algeria", "Algeria", "Algérie"],
    "EC": ["Ecuador", "Ecuador", "Équateur", "Equador"],
    "EE": ["Estonia", "Estonia", "Estonie"],
    "EG": ["Egypt", "Egitto", "Égypte"],
    "EH": ["Western Sahara", "Sahara Occidentale", "Sahara occidental"],
    "ER": ["Eritrea", "Eritrea", "Érythrée"],
    "ES": ["Spain", "Spagna", "Espagne"],
    "ET": ["Ethiopia", "Etiopia", "Éthiopie"],
    "FK": ["Falkland Islands", "Isole Falkland", "Îles Malouines"],
    "FI": ["Finland", "Finlandia", "Finlande"],
    "FJ": ["Fiji", "Figi", "Fidji"],
    "FR": ["France", "Francia", "France"],
    "GA": ["Gabon", "Gabon", "Gabon"],
    "GB": ["United Kingdom", "Regno Unito", "Royaume-Uni"],
    "GE": ["Georgia", "Georgia", "Géorgie"],
    "GF": ["French Guiana", "Guyana francese", "Guyane française"],
    "GH": ["Ghana", "Ghana", "Ghana"],
    "GL": ["Greenland", "Groenlandia", "Groenland"],
    "GM": ["Gambia", "Gambia", "Gambie"],
    "GN": ["Guinea", "Guinea", "Guinée"],
    "GQ": ["Equatorial Guinea", "Guinea Equatoriale", "Guinée équatoriale"],
    "GR": ["Greece", "Grecia", "Grèce"],
    "GT": ["Guatemala", "Guatemala", "Guatemala"],
    "GW": ["Guinea-Bissau", "Guinea-Bissau", "Guinée-Bissau"],
    "GY": ["Guyana", "Guyana", "Guyana"],
    "HN": ["Honduras", "Honduras", "Honduras"],
    "HR": ["Croatia", "Croazia", "Croatie"],
    "HT": ["Haiti", "Haiti", "Haïti"],
    "HU": ["Hungary", "Ungheria", "Hongrie"],
    "ID": ["Indonesia", "Indonesia", "Indonésie"],
    "IE": ["Ireland", "Irlanda", "Irlande"],
    "IL": ["Israel", "Israele", "Israël"],
    "IN": ["India", "India", "Inde"],
    "IQ": ["Iraq", "Iraq", "Irak"],
    "IR": ["Iran", "Iran", "Iran"],
    "IS": ["Iceland", "Islanda", "Islande"],
    "IT": ["Italy", "Italia", "Italie"],
    "JM": ["Jamaica", "Giamaica", "Jamaïque"],
    "JO": ["Jordan", "Giordania", "Jordanie"],
    "JP": ["Japan", "Giappone", "Japon"],
    "KE": ["Kenya", "Kenya", "Kenya"],
    "KG": ["Kyrgyzstan", "Kirghizistan", "Kirghizistan"],
    "KH": ["Cambodia", "Cambogia", "Cambodge"],
    "KP": ["North Korea", "Corea del Nord", "Corée du Nord"],
    "KR": ["South Korea", "Corea del Sud", "Corée du Sud"],
    "XK": ["Kosovo", "Kosovo", "Kosovo"],
    "KW": ["Kuwait", "Kuwait", "Koweït", "Kuweit"],
    "KZ": ["Kazakhstan", "Kazakistan", "Kazakhstan"],
    "LA": ["Laos", "Laos", "Laos"],
    "LB": ["Lebanon", "Libano", "Liban"],
    "LK": ["Sri Lanka", "Sri Lanka", "Sri Lanka"],
    "LR": ["Liberia", "Liberia", "Liberia"],
    "LS": ["Lesotho", "Lesotho", "Lesotho", "Lesoto"],
    "LT": ["Lithuania", "Lituania", "Lituanie"],
    "LU": ["Luxembourg", "Lussemburgo", "Luxembourg"],
    "LV": ["Latvia", "Lettonia", "Lettonie"],
    "LY": ["Libya", "Libia", "Libye", "Libie"],
    "MA": ["Morocco", "Marocco", "Maroc"],
    "MD": ["Moldova", "Moldavia", "Moldavie"],
    "ME": ["Montenegro", "Montenegro", "Monténégro"],
    "MG": ["Madagascar", "Madagascar", "Madagascar"],
    "MK": ["North Macedonia", "Macedonia del Nord", "Macédoine du Nord"],
    "ML": ["Mali", "Mali", "Mali"],
    "MM": ["Myanmar", "Myanmar", "Myanmar"],
    "MN": ["Mongolia", "Mongolia", "Mongolie"],
    "MR": ["Mauritania", "Mauritania", "Mauritanie"],
    "MW": ["Malawi", "Malawi", "Malawi"],
    "MX": ["Mexico", "Messico", "Mexique"],
    "MY": ["Malaysia", "Malaysia", "Malaisie"],
    "MZ": ["Mozambique", "Mozambico", "Mozambique"],
    "NA": ["Namibia", "Namibia", "Namibie"],
    "NC": ["New Caledonia", "Nuova Caledonia", "Nouvelle-Calédonie"],
    "NE": ["Niger", "Niger", "Niger"],
    "NG": ["Nigeria", "Nigeria", "Nigéria"],
    "NI": ["Nicaragua", "Nicaragua", "Nicaragua"],
    "NL": ["Netherlands", "Paesi Bassi", "Pays-Bas", "Olanda", "Holland", "Olande"],
    "NO": ["Norway", "Norvegia", "Norvège"],
    "NP": ["Nepal", "Nepal", "Népal"],
    "NZ": ["New Zealand", "Nuova Zelanda", "Nouvelle-Zélande"],
    "OM": ["Oman", "Oman", "Oman"],
    "PA": ["Panama", "Panama", "Panama"],
    "PE": ["Peru", "Perù", "Pérou"],
    "PG": ["Papua New Guinea", "Papua Nuova Guinea", "Papouasie-Nouvelle-Guinée"],
    "PH": ["Philippines", "Filippine", "Philippines"],
    "PL": ["Poland", "Polonia", "Pologne"],
    "PK": ["Pakistan", "Pakistan", "Pakistan"],
    "PR": ["Puerto Rico", "Porto Rico", "Porto Rico"],
    "PS": ["Palestine", "Palestina", "Palestine"],
    "PT": ["Portugal", "Portogallo", "Portugal"],
    "PY": ["Paraguay", "Paraguay", "Paraguay"],
    "QA": ["Qatar", "Qatar", "Qatar"],
    "RO": ["Romania", "Romania", "Roumanie"],
    "RS": ["Serbia", "Serbia", "Serbie"],
    "RU": ["Russia", "Russia", "Russie"],
    "RW": ["Rwanda", "Ruanda", "Rwanda"],
    "SA": ["Saudi Arabia", "Arabia Saudita", "Arabie saoudite"],
    "SB": ["Solomon Islands", "Isole Salomone", "Îles Salomon", "isole salomon"],
    "SD": ["Sudan", "Sudan", "Soudan"],
    "SE": ["Sweden", "Svezia", "Suède"],
    "SI": ["Slovenia", "Slovenia", "Slovénie"],
    "SJ": ["Svalbard and Jan Mayen", "Svalbard e Jan Mayen", "Svalbard et Jan Mayen"],
    "SK": ["Slovakia", "Slovacchia", "Slovaquie"],
    "SL": ["Sierra Leone", "Sierra Leone", "Sierra Leone"],
    "SN": ["Senegal", "Senegal", "Sénégal"],
    "SO": ["Somalia", "Somalia", "Somalie"],
    "SR": ["Suriname", "Suriname", "Suriname"],
    "SS": ["South Sudan", "Sudan del Sud", "Soudan du Sud"],
    "SV": ["El Salvador", "El Salvador", "Salvador"],
    "SY": ["Syria", "Siria", "Syrie"],
    "SZ": ["Eswatini", "Eswatini", "Eswatini"],
    "TD": ["Chad", "Ciad", "Tchad"],
    "TF": ["French Southern and Antarctic Lands", "Territori Francesi del Sud", "Terres australes et antarctiques françaises"],
    "TG": ["Togo", "Togo", "Togo"],
    "TH": ["Thailand", "Thailandia", "Thaïlande", "Tailandia"],
    "TJ": ["Tajikistan", "Tagikistan", "Tadjikistan"],
    "TL": ["East Timor", "Timor Est", "Timor-Leste"],
    "TM": ["Turkmenistan", "Turkmenistan", "Turkménistan"],
    "TN": ["Tunisia", "Tunisia", "Tunisie"],
    "TR": ["Turkey", "Turchia", "Turquie"],
    "TT": ["Trinidad and Tobago", "Trinidad e Tobago", "Trinité-et-Tobago"],
    "TW": ["Taiwan", "Taiwan", "Taïwan"],
    "TZ": ["Tanzania", "Tanzania", "Tanzanie"],
    "UA": ["Ukraine", "Ucraina", "Ukraine"],
    "UG": ["Uganda", "Uganda", "Ouganda"],
    "US": ["United States", "Stati Uniti", "États-Unis", "USA"],
    "UY": ["Uruguay", "Uruguay", "Uruguay"],
    "UZ": ["Uzbekistan", "Uzbekistan", "Ouzbékistan"],
    "VE": ["Venezuela", "Venezuela", "Venezuela"],
    "VN": ["Vietnam", "Vietnam", "Vietnam"],
    "VU": ["Vanuatu", "Vanuatu", "Vanuatu"],
    "YE": ["Yemen", "Yemen", "Yémen"],
    "ZA": ["South Africa", "Sudafrica", "Afrique du Sud"],
    "ZM": ["Zambia", "Zambia", "Zambie"],
    "ZW": ["Zimbabwe", "Zimbabwe", "Zimbabwe"]
}